### ISSUE TITLE
no charts for 2.11.3+

### ISSUE THREAD

**Issue by fireba11** [traefik/traefik-helm-chart#1226]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Is there a specific reason there are no more helm charts for 2.11 after 2.11.2?
Yes, you can override the container version used, but there might be other changes the chart needs to account for and this could cause people to run old versions needlessly.

**Comment by mloiseleur** [comment]
Hello @fireba11,

This chart is community driven. It's mainly because no one opened a PR on it. 
The branch `v27` can be used to publish a new version. As you noticed, the last major version of this Chart compatible with v2.11, v27.x, can be used with v2.11.2+ by overriding the container version.
There is no [documented required changes](https://doc.traefik.io/traefik/migration/v2/#v2113) needed between v2.11.2 and later v2.11.x version.
Anyway, if you need it, feel free to open a PR. It should target branch v27.

Does that answer your question ?

**Comment by fireba11** [comment]
Jup, thx.
