### ISSUE TITLE
Expose serverstransport options in Values.yaml

### ISSUE THREAD

**Issue by SlavikCA** [traefik/traefik-helm-chart#1273]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I'm running Traefik in my Harvester kubernetes cluster.
Version 33.1.0.

One of the pods has a service, which only exposes port 443 with self-generated SSL certificate.

How can I make Traefik to proxy to it?

Eventually, I was able to do that with this entry in values.yaml:
```yaml
additionalArguments:
  - "--serverstransport.insecureskipverify=true"
```

Is it right way? 
Can the servertransport options be exposed directly?

**Comment by mloiseleur** [comment]
Thanks for reaching out!

There is a [complete example in upstream doc](https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-serverstransport) about how to configure connection between traefik and backends using ServersTransports.

To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly. 
 
Since this issue is about how to configure Traefik, not related to the Chart, I'm closing it. 

Feel free to re-open it or open a new one if needed.
