### ISSUE TITLE
Consider Pre-Release (RC) Chart Versions

### ISSUE THREAD

**Issue by SantoDE** [traefik/traefik-helm-chart#338]
## Feature

We have received feedback, that the community would be willing to try out RC versions through Helm Charts, rather than having to manually install that.

This is possible, based on the fact that helm handles pre-release versions differently and they can be searched for in the repository by adding the `--devel` argument.

```
helm search repo traefik --versions --devel
```

Before we do so, we need to answer 2 questions first:

- How do we handle the code? Do we need to have a seperate branch per appVersion? (I personally don't think so)
- How do we handle the exact versioning? Do we freeze merging PR's once we enter an RC phase? i.e. we have chart version 9.12.0-rc1 which would also bump the appVersion to 2.X-rc1. Do we stop merging in the meantime, as we entered an RC?

Feedback welcomed, so we can evaluate the process for Traefik 2.5 and above.

**Comment by loreleimccollum-work** [comment]
I think I would keep it all it the same branch until you find a use case that makes it necessary to have branches per appversion etc.. I think its a little tricky since your chart version != app version.. but you could just append the -rc1 as you suggest to the chart version ( its already in the app version) and publish that.  Can always start with something and tweak it as more people adopt and use the rc candidates and then adapt from there

**Comment by mloiseleur** [comment]
It would be nice to provide an option / a pre-release for [Traefik Proxy 3 Beta](https://traefik.io/blog/traefik-proxy-3-0-scope-beta-program-and-the-first-feature-drop/)

**Comment by mloiseleur** [comment]
We are providing an option to test new version of Traefik with `image.tag`.
