### ISSUE TITLE
allow `spec.strategy` to be `Recreate` in deployment

### ISSUE THREAD

**Issue by rxbn** [traefik/traefik-helm-chart#355]
At the moment, `RollingUpdate` is hard-coded as the update strategy for Traefik deployment. Please create a value to change the strategy to `Recreate` since this is required for RWO PVCs.

**Comment by faust64** [comment]
@rxbn : can you check your values file? What is your `rollingUpdate.maxUnavailable`?

The default value in traefik chart would set it to `1`. Then, updating your Deployment, the previous Pod should terminate while the new one starts up. We might see a few multi-attach errors, though they won't last.
Just make sure you keep that default - otherwise, Kubernetes would set it to 25%, and then the new Pod would be stuck.

**Comment by jalberto** [comment]
Currently, it is set to `0` by default, so you need to use `Recreate`
