### ISSUE TITLE
Default global options like `--global.sendanonymoususage` are not easily changeable

### ISSUE THREAD

**Issue by thardeck** [traefik/traefik-helm-chart#357]
It would be helpful to templatize options like `--global.sendanonymoususage` to allow them do be disabled during installation.
https://github.com/traefik/traefik-helm-chart/blob/6b4c3642141087cc8c92a201a3d8b7ccdec9c1d5/traefik/values.yaml#L178

At the moment disabling of these options seems to be quite hacky.

**Comment by jakubhajek** [comment]
The following can be disabled by deploying Traefik using  `--set "globalArguments="`.
 It will set `globalArguments` to an empty object and disable `checknewversion` and `sendanonymoususage` features.

**Comment by SantoDE** [comment]
Closed as there is a workaround by @jakubhajek

**Comment by thardeck** [comment]
> The following can be disabled by deploying Traefik using `--set "globalArguments="`.
> It will set `globalArguments` to an empty object and disable `checknewversion` and `sendanonymoususage` features.

This is what we did but what if I want one of these options to be active? Or what happens if you add new options which would be unintentionally disabled by this?

**Comment by jakubhajek** [comment]
One of the solutions is to define the file' values.yaml`  with all configuration that is required including `globalArguments `instead of managing through imperative commands. Going further, it would be worth considering implementing GitOps and managing a cluster state, installing Helm packages through Git repository. 
As it is not a bug I invite you to continue the conversation on the  [community forum.](https://community.traefik.io/)
