### ISSUE TITLE
How to scale traefik in kubernetes

### ISSUE THREAD

**Issue by StarpTech** [traefik/traefik-helm-chart#403]
Hi,

if we enable `persistence` to persist our TLS certificates we can't scale with `deployment` approach because a volume from type `ReadWriteOnce` can't be mounted by multiple pods. What's the approach here to handle this with minimal effort? Literally, just setting `replicas: 2` will not work.

**Comment by faust64** [comment]
Hi,

You would not b e able to have several replicas deployed when persistence is enabled.
Are you using LetsEncrypt certificates? Or installing your own, into that PVC?

With LetsEncrypt, that Chart won't let you do this. While setting it up manually may not be recommended.
In those cases, I would usually configure LetsEncrypt out of Kubernetes, have a pair of LBs, and make sure only one of them would request/renew certificates at once - as well as sync the resulting /etc/letsencrypt to the other balancers and trigger a configuration reload over a period of time, ... Then, use Traefik self-signed certificates, or some internal CA/server certificate, re-encrypting those connections in between the front LBs and Kubernetes.

Otherwise, assuming you have your own certificate(s), one way to work around this would be to create a Secret with your public and private keys, using something like `kubectl create secret -n <traefik-ns> tls custom-traefik-certificate --cert=./public.crt --key=./private.key`.

In addition to that Secret, I would usually create a ConfigMap, such as:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-traefik-config
  namespace: <traefik-ns>
data:
  tls.toml: |
    [[tls.certificates]]
      certFile = "/tls-secret/tls.crt"
      keyFile = "/tls-secret/tls.key"
      stores = ["default"]
    [tls.stores]
      [tls.stores.default]
        [tls.stores.default.defaultCertificate]
          certFile = "/tls-secret/tls.crt"
          keyFile = "/tls-secret/tls.key"
```

(which may even be too much)

Next, make sure those ConfigMap and Secret are mounted into your Traefik container, adding to your values:

```
volumes:
  - name: custom-traefik-config
    mountPath: /static
    type: ConfigMap
  - name: custom-traefik-certificate
    mountPath: /tls-secret
    type: Secret
```

Then, we need to tell Traefik to load read the configuration from our ConfigMap, adding to our values:

```
additionalArguments:
  - --providers.file
  - --providers.file.directory=/static
[...]
```

Now, you may use either a DaemonSet, or stick with a Deployment and scale it beyond a single Pod.

And... apparently, there would be a simpler way to do this, as pointed out here: https://github.com/traefik/traefik-helm-chart/issues/187#issuecomment-816146876
Create a TLSStore object, that would point to your Secret ( https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-tlsstore ).

**Comment by StarpTech** [comment]
Hi @faust64 thanks for the write-up. Indeed, I'm planning to move CA handling out of traefik via DNS with cert-manager. This is really sad because it worked very well. After some research, I found out that "Distributed Let's Encrypt" is an enterprise feature.

**Comment by SantoDE** [comment]
Thanks @faust64 for the answers.

I think the question is answered and thus, I gonna close that issue :)
