### ISSUE TITLE
apiextensions.k8s.io/v1beta1 is deleted in Kubernetes v1.22

### ISSUE THREAD

**Issue by brandond** [traefik/traefik-helm-chart#438]
I am preparing K3s for Kubernetes v1.22, and it appears that the Traefik Helm chart is still using `v1beta1` CRDs. This API version is going away in v1.22; the Helm charts do not work in their current state. 

As per https://github.com/kubernetes/sig-release/tree/master/releases/release-1.22 Kubernetes 1.22 is expected Wednesday, August 4th; it would be nice if the Traefik helm charts supported this release on day 1. beta.0 is out now, for anyone who wants to experiment with it.

**Comment by sdwire** [comment]
I would also like to see this -- for the same reason.

A bit of interesting (and confusing) history:

This issue was reported as #303 and resolved in #327 ([commit](https://github.com/traefik/traefik-helm-chart/commit/493df91013a61d4fd51cf826c886be6c2bf74999#diff-2c4571698325c1ef83b20b866ff3f9293f0cafbd56833a8a55742e59f82da2c9))
But then, it was reverted the next day by [another commit](https://github.com/traefik/traefik-helm-chart/commit/db26e8e834c43d06e17bd68102a4095476147b7d#diff-2c4571698325c1ef83b20b866ff3f9293f0cafbd56833a8a55742e59f82da2c9), with no apparent explanation as to why it was reverted.
