### ISSUE TITLE
How to migrate from v1 legacy helm chart?? Mapping of settings

### ISSUE THREAD

**Issue by nodesocket** [traefik/traefik-helm-chart#542]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I'm guessing all the custom specific Helm settings got removed from `values.yaml` and instead we have to manually map the settings previously defined as Helm `key:values` into strings in `additionalArguments: []`. It would be extremely helpful to get a mapping of legacy helm `key:value` settings into their corresponding additionalArguments.

I.E. 

```
ssl: *
kvprovider: *
acme: *
gzip.enabled: true
forwardedHeaders.enabled: true
forwardedHeaders.trustedIPs: []
```

**Comment by mloiseleur** [comment]
Hello @nodesocket,

Thanks for this issue and your interest on Traefik.

There is a [complete migration guide](https://doc.traefik.io/traefik/migration/v1-to-v2/).
There has been many (breaking) changes since last version of Traefik v1, and so there is not really a mapping between v1 config and v2 config. 

I'll close this issue but feel free to open a PR if you think you have a way to provide this mapping or (at least) some help for users coming from v1.
