### ISSUE TITLE
Latest chart version (19.0.0) fails to install

### ISSUE THREAD

**Issue by remenaker** [traefik/traefik-helm-chart#698]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

19.0.0

### What version of Traefik are you using?

2.9.4

### What did you do?

When installing with `helm install traefik traefik/traefik` install fails

### What did you see instead?

Fails with error Error: INSTALLATION FAILED: execution error at (traefik/templates/ingressclass.yaml:10:8): ERROR: You must use at least Kubernetes v1.16 with this Chart

### What is your environment & configuration?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-6d3986b", GitCommit:"8877a3e28d597e1184c15e4b5d543d5dc36b083b", GitTreeState:"clean", BuildDate:"2022-07-20T22:05:32Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

### Additional Information

```shell
It seems that this chart version has a typo in the ingressclass.yaml file on line 7 
https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/ingressclass.yaml#L7
```

**Comment by nicely-dunn** [comment]
[This is a problem specific to EKS users, I think.](https://github.com/helm/helm/issues/10375) The logic Traefik uses in the ingressclass.yaml [skips pre-release versions](https://helm.sh/docs/chart_template_guide/function_list/#working-with-prerelease-versions) and since AWS is versioning their releases how semver interprets pre-release versions the logic falls back to the else block.

Traefik could either implement a roundabout way of comparing versions so that EKS versions also get checked (potentially having to allow all pre-release versions), or the simply add an override to the values.yaml that allows a user to set the Kubernetes version manually. The latter I've seen used in other charts before.

See also: [Use correct SemVer for Kubernetes version](https://github.com/aws/containers-roadmap/issues/1404)

**Comment by mloiseleur** [comment]
The fix was easy : it's possible to include pre-release with -0 at the end of version when using semverCompare. 
Thanks for your report @remenaker and thanks for your analysis @nicely-dunn.
