### ISSUE TITLE
Support setting `loadBalancerClass` in Service spec

### ISSUE THREAD

**Issue by z0rc** [traefik/traefik-helm-chart#826]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class

I'd like to set this field in Traefik's Service of type LoadBalancer, when using with NLB managed by AWS LBC, see https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.5/guide/service/nlb/#configuration

**Comment by mloiseleur** [comment]
Hello @z0rc,

Thanks for your suggestion, it makes a lot of sense.  Unfortunately, this would not make it to our roadmap for a while as we are focused elsewhere.  If you or another community member would like to build it, let us know and we will work with you to make sure you have all the information needed so that it can be merged.  

Don’t forget to check out the [contributor docs] (https://github.com/traefik/traefik-helm-chart/blob/master/CONTRIBUTING.md) and to link the PR to this issue.

**Comment by project0** [comment]
Will be available in the next helm release ;-)
