### ISSUE TITLE
Error while updating to Traefik version 2.9.9

### ISSUE THREAD

**Issue by farooq31325** [traefik/traefik-helm-chart#828]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

21.2.0

### What version of Traefik are you using?

2.9.8

### What did you do?

We are upgrading traefik version from 2.9.8 to 2.9.9.

While upgrading, we are receiving error in logs 

`{"ACME CA":"[https://acme-v02.api.letsencrypt.org/directory","level":"error","msg":"Unable](https://acme-v02.api.letsencrypt.org/directory%22,%22level%22:%22error%22,%22msg%22:%22Unable) to obtain ACME certificate for domains \"domain.com\": unable to generate a certificate for the domains [domain.com]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: Error creating new order :: too many failed authorizations recently: see [https://letsencrypt.org/docs/failed-validation-limit/","providerName":"le.acme","routerName":"traefik-forward-authserverhttps-ae666fdd12603d0225d0@kubernetescrd","rule":"Host(`domain.com`)","time":"2023-04-17T07:29:05Z"}](https://letsencrypt.org/docs/failed-validation-limit/%22,%22providerName%22:%22le.acme%22,%22routerName%22:%22traefik-forward-authserverhttps-ae666fdd12603d0225d0@kubernetescrd%22,%22rule%22:%22Host(%60domain.com%60)%22,%22time%22:%222023-04-17T07:29:05Z%22%7D)` 

Also our Pod is going in crashloop please refer below screen shot
![image](https://user-images.githubusercontent.com/130972631/232432271-296575d4-443d-4c82-b653-5d45848266a1.png)

### What did you see instead?

Acme error

### What is your environment & configuration?

AKS Platform on yaml configuration.

**Comment by mloiseleur** [comment]
Hello @farooq31325, 

Thanks for reaching out! 

This issue is not related to the upgrade. It seems traefik is not able to renew certificates and is rate limited from let's encrypt, ie receiving `429 too many failed authorizations recently`. 

Following error message, it seems there is a router configured on `domain.com`:
```json
"routerName":"traefik-forward-authserverhttps-ae666fdd12603d0225d0@kubernetescrd","rule":"Host(domain.com)"
```

To keep this repository focused on helm chart related issue, we ask that all questions be asked in the [community forum] (https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.
