### ISSUE TITLE
Make it easier to upgrade Traefik using Helm

### ISSUE THREAD

**Issue by trondhindenes** [traefik/traefik-helm-chart#947]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I'd really like to see some official guidance from Traefik on how to install/upgrade Traefik using Helm. Because of the "CRDs aren't updated" bug/feature in Helm, it's currently extremely difficule to manage Traefik versions using Helm alone.

Right now now trying to go from 2.9 to 2.10, and the helm chart fails because the CRDs namespaces are now different.

IMHO the natural thing to do would be to offer one CRD chart, and one Traefik chart, and document that users need to apply the CRD chart first.

**Comment by mloiseleur** [comment]
Hello,

I'm not sure to fully understand you :thinking:.

1. As far as I know, there is no namespace on CRDs: it's cluster-wide
2. There is guidance in the [README](https://github.com/traefik/traefik-helm-chart#upgrading-crds) using one kubectl command.

Would you please detail how managing two charts, linked to each other, would be better than a simple command ?

**Comment by bennesp** [comment]
I think that @trondhindenes means the "Kubernetes CRDs API Group" with "namespace", that from 2.9 to 2.10 was changed from `traefik.containo.us` to `traefik.io`, as documented here: https://doc.traefik.io/traefik/migration/v2/#kubernetes-crds

If I interpreted correctly, this is already documented: for example, looking at [release v22.3.0](https://github.com/traefik/traefik-helm-chart/releases/tag/v22.3.0), you can see a warning:


> => ⚠️ You need to update CRDs ⚠️
> 
> Beware that Helm is not updating CRDs. More details [here](https://github.com/traefik/traefik-helm-chart#upgrading-crds).
> This chart will update RBAC to use those new CRDs.


With the link to the README section that explains how to deal with this change

**Comment by Xitric** [comment]
@mloiseleur If I may tune in on this discussion. We have similarly looked for an official option to update the Traefik CRDs via a separate chart as opposed to executing a command against the cluster. Our reasoning is this:

1. We use Flux for declaratively managing resources in our cluster. Executing a command against our clusters in not declarative, but rather imperative, and no history of this upgrade is visible from our git history.
2. Due to using Flux with a git repository, we have a chance to review changes made against our cluster in our team via Pull Requests. Executing a command against a production cluster would not be subject to this type of review.
3. Due to Flux pulling configuration from a git repository, we can isolate our clusters on private networks with no administrator access. We only open access during break-the-glass scenarios. We would much appreciate if upgrading CRDs is not break-the-glass.

Right now we are looking at managing this CRD chart on our own, but it would be valuable if it was maintained officially 🙂

**Comment by mloiseleur** [comment]
@Xitric Sure, you may :).

In FluxCD, you can manage pure yaml and then, you won't suffer Helm limitations.

Without moving to pure yaml, in the `HelmRelease` CRD of Helm controller there is a [crd option during upgrade](https://fluxcd.io/flux/components/helm/api/v2beta1/#helm.toolkit.fluxcd.io/v2beta1.Upgrade) to tell flux to override default helm behavior on CRD with `CreateReplace` instead of `Create`.

Would this solve your issue ?

If you are in a use case where it's not, feel free to submit a PR in order to provide CRDs separately in an other chart on this repo. It would also probably help v3 beta users.

**Comment by Xitric** [comment]
@mloiseleur Thank you for the swift feedback!

I had completely forgotten about that setting in Flux for overriding the CRD policy. We will certainly look into whether that can be of use to us. If not, we will look into contributing a CRD Helm chart, but it sounds like we will not be needing that after all.
