### ISSUE TITLE
Could not upgrade latest traefik helm chart version 25.0.0

### ISSUE THREAD

**Issue by berchc** [traefik/traefik-helm-chart#968]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

25.0.0

### What version of Traefik are you using?

2.10.5

### What did you do?

The current helm chart version we use is 23.1.0 with traefik image version 2.10.3.
we are trying to upgrade the helm chart version to 25.0.0 with traefik image version 2.10.5 (we checked that there is no 3.0.0 release version only pre-release version available).

### What did you see instead?

Upgrade failed with the below error :
/opt/hostedtoolcache/helm/3.10.1/x64/linux-amd64/helm upgrade --namespace traefik --install --values /agent/_work/17/postaksdev/artifacts/traefik/rabowings_values.yaml --wait traefik /agent/_work/17/postaksdev/artifacts/traefik/charts
Error: template: traefik/templates/rbac/clusterrole.yaml:48:13: executing "traefik/templates/rbac/clusterrole.yaml" at <semverCompare "<3.0.0-0" (include "imageVersion" $)>: error calling semverCompare: Invalid Semantic Version
Release "traefik" does not exist. Installing it now.
##[error]Error: template: traefik/templates/rbac/clusterrole.yaml:48:13: executing "traefik/templates/rbac/clusterrole.yaml" at <semverCompare "<3.0.0-0" (include "imageVersion" $)>: error calling semverCompare: Invalid Semantic Version

### What is your environment & configuration?

Yaml

**Comment by Borrelworst** [comment]
To add to this:

What we do with the traefik images, we don't run them directly from dockerhub into our clusters, but first download them and put them in our own registry. When then also put our own tags on it, so our tags will be in the form of data.buildID (for example 20231122.1234567). As far as I can see, this retagging is causing the actual issue, as it expects the tag to be the exact same tag as you have used in Dockerhub.

If would be better to base this on just the chart version, instead of also checking the image version.

**Comment by mloiseleur** [comment]
Traefik Proxy and this chart follows semver, not calver.

It cannot use the chart version, because this Chart is now used by Traefik v2 and Traefik v3 user. 
By using Chart version, I don't see how it can still work for both v2 and v3 user. 

Since it's really specific to your environment, I close this issue.

Feel free to submit a PR if you think you can do it without breaking for both v2 and v3 user.
